# standard jekyll configuration

permalink: /:title

pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount
org: org-ruby


# configuration required for some pages

baseurl:    /pelm
url: "http://caker.me/pelm/"

title: aStock
author: eggcaker
email: eggcaker@gmail.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

github:
  username: eggcaker

# disqus:
#   id: disqusid
